@startuml

class Holder {
+ Holder(size, data)
+ size()
+ data()
+ {method}...
}

class DataContainer {
+ DataContainer(size, args...)
+ DataContainer(values, args...)
+ DataContainer(iterable, args...)
+ fill(value)
+ range(min, step)
+ linspace(min, max)
+ generate(function, args...)
+ apply(function, args...)
}

class Raster {
+ Raster(shape, args...)
+ Raster(shape, values, args...)
+ Raster(shape, iterable, args...)
+ shape()
+ domain()
+ dimension()
+ length(axis)
+ operator[](position)
+ at(position)
+ section(front, back)
+ section(index)
}

class ContiguousContainerMixin {
+ empty()
+ operator[](index)
+ begin()
+ end()
+ operator==()
+ operator!=()
}

class ArithmeticMixin {
+ operator+=(rhs)
+ operator-=(rhs)
+ operator*=(rhs)
+ operator/=(rhs)
+ {method}...
}

class MathFunctionsMixin {
+ abs()
+ min(rhs)
+ max(rhs)
+ sin()
+ cos()
+ exp()
+ log()
+ pow(rhs)
+ {method}...
}

ContiguousContainerMixin <|-- DataContainer
Holder <|-- DataContainer
DataContainer <|-- Raster
ArithmeticMixin <|-- Raster
MathFunctionsMixin <|-- Raster
@enduml