@startuml
class DataContainerHolder {
# m_container
+ size()
+ data()
}

class DataContainer {
+ container()
+ moveTo(container)
}

class Raster {
- m_shape
+ shape()
+ domain()
+ dimension()
+ length(axis)
+ operator[](position)
+ at(position)
+ section(front, back)
+ section(index)
}

class ContiguousContainerMixin {
+ empty()
+ operator[](index)
+ begin()
+ end()
+ operator==()
+ operator!=()
}

class ArithmeticMixin {
+ operator+=(rhs)
+ operator-=(rhs)
+ operator*=(rhs)
+ operator/=(rhs)
+ generate(function, args...)
+ apply(function, args...)
}

class MathFunctionsMixin {
+ abs()
+ min(rhs)
+ max(rhs)
+ sin()
+ cos()
+ exp()
+ log()
+ pow(rhs)
+ {method}...
}

ContiguousContainerMixin <|-- DataContainer
ArithmeticMixin <|-- DataContainer
DataContainerHolder <|-- DataContainer
DataContainer <|-- Raster
MathFunctionsMixin <|-- Raster
@enduml