// SPDX-FileCopyrightText: Copyright (C) 2024, Antoine Basset
// SPDX-PackageSourceInfo: https://github.com/kabasset/Linx
// SPDX-License-Identifier: Apache-2.0

#ifndef LINX_RUN_FLOW_H
#define LINX_RUN_FLOW_H

#include "Linx/Run/PipelineTasks.h"

#include <string>
#include <tuple>

namespace Linx {

/**
 * Policy tag to overwrite.
 */
struct Overwrite;

/**
 * Policy tag to insert at given position.
 */
template <std::integral auto I>
struct Insert;

/**
 * Policy tag to append.
 */
using Append = Insert<-1>;

/**
 * Policy tag to prepend.
 */
using Prepend = Insert<0>;

/**
 * @brief Workflow context.
 */
template <typename TLogger>
class FlowContext {
public:

  using Logger = TLogger;

  FlowContext(const std::string& label, TLogger& logger) : m_label(label), m_logger(logger) {}

  const std::string& label() const
  {
    return m_label;
  }

  void log(auto&&... args)
  {
    m_logger(m_label, LINX_FORWARD(args)...);
  }

private:

  std::string m_label;
  TLogger& m_logger;
};

/**
 * @brief No-logger specialization.
 */
template <>
class FlowContext<void> {
public:

  FlowContext(const std::string& label) : m_label(label) {}

  const std::string& label() const
  {
    return m_label;
  }

  void log(auto&&...) {}

private:

  std::string m_label;
};

/**
 * @brief Workflow state.
 * 
 * A workflow is a sequence of tasks which produce possibly multivalued states.
 * The API provides a syntax for the creation and execution of workflows.
 * The benefits wrt. classical function calls are:
 * - No need for named intermediate variables: they are part of the states already;
 * - Embedded logging and/or benchmarking tools.
 * 
 * The workflow is started with some context and input states,
 * and then successive anonymous states are generated by user-provided tasks.
 * States hold arbitratily complex values, which are explicit inputs or the results of tasks.
 * The workflow outputs are obtained through structured bindings, so that a typical workflow is of the form:
 * 
 * \code
 * auto [out_0, out_1, ... , out_l] = Linx::Flow("Workflow name", logger) // Start workflow
 *     .append(in_0, in_1, ... , in_m) // Add inputs
 *     .run(task_0, task_1, ... , task_n); // Pipe tasks
 * \endcode
 * 
 * Tasks can act on one, some or all inputs at once, and return one or several outputs.
 * 
 * The API is a tiny wrapper:
 * if the i-th state is composed of values `value_0, value_1, ... , value_n`,
 * then `state_i.run(task_i)` produces a (possibly multivalued) state `task_i(value_0, value_1, ... , value_n)`.
 * 
 * The above example corresponds to the following pseudo-code:
 * 
 * \code
 * tmp[0] = in
 * for i in [0, n]:
 *   tmp[i] = task[i](tmp[i-1])
 *   log task[i] parameters and elapsed time
 * out = tmp[n]
 * \endcode
 * 
 * where input, output and temporary states may be multivalued.
 */
template <typename TContext, typename... TValues>
class Flow {
public:

  /**
   * Initial state constructor without logger.
   */
  Flow(const std::string& label) : m_context(label), m_values() {}

  /**
   * Initial state constructor.
   */
  Flow(const std::string& label, auto& logger) : m_context(label, logger), m_values() {}

  /**
   * Constructor.
   */
  Flow(TContext context, const std::string& message, TValues... values) :
      Flow(LINX_MOVE(context), message, std::make_tuple(LINX_MOVE(values)...))
  {}

  /**
   * Constructor.
   */
  Flow(TContext context, const std::string& message, std::tuple<TValues...> values) :
      m_context(LINX_MOVE(context)),
      m_values(LINX_MOVE(values))
  {
    m_context.log(message);
  }

  /**
   * Get the i-th value.
   */
  template <auto I>
  decltype(auto) get()
  {
    return std::get<I>(m_values);
  }

  /**
   * Append values.
   */
  auto append(auto&&... values)
  {
    return make_state<Append>("Input", std::forward_as_tuple(values...));
  }

  /**
   * Prepend values.
   */
  auto prepend(auto&&... values)
  {
    return make_state<Prepend>("Input", std::forward_as_tuple(values...));
  }

  /**
   * Run a task.
   * 
   * @tparam TPolicy The transition policy (`Overwrite`, `Append` or `Prepend`)
   */
  template <typename TPolicy = Overwrite> // FIXME allow Insert<I>?
  auto run(auto&& task) // FIXME variadic
  {
    auto task_label = label(task);
    auto out = eval(LINX_FORWARD(task), m_values, std::make_index_sequence<sizeof...(TValues)>());
    return make_state<TPolicy>(task_label, LINX_MOVE(out));
  }

  template <typename TPolicy = Overwrite>
  auto run(auto&& task0, auto&&... tasks)
  {
    return run<TPolicy>(LINX_FORWARD(task0)).template run<TPolicy>(LINX_FORWARD(tasks)...);
    //FIXME run<Next<TPolicy>>(tasks...)
  }

  /**
   * Run a task and append the results.
   */
  auto append_run(auto&&... tasks)
  {
    return run<Append>(LINX_FORWARD(tasks)...);
  }

  /**
   * Run a task and prepend the results.
   */
  auto prepend_run(auto&&... tasks)
  {
    return run<Prepend>(LINX_FORWARD(tasks)...);
  }

  template <typename TPolicy = Overwrite>
  auto generate(auto... funcs)
  {
    return run<TPolicy>(Pipeline::Generate(LINX_MOVE(funcs)...)); // FIXME simplify implementation
  }

  auto append_generate(auto&&... funcs)
  {
    return generate<Append>(LINX_FORWARD(funcs)...);
  }

  auto prepend_generate(auto&&... funcs)
  {
    return generate<Prepend>(LINX_FORWARD(funcs)...);
  }

  /**
   * Apply an element-wise functions as a new instance.
   */
  template <typename TPolicy = Overwrite>
  auto apply(auto&&... funcs)
  {
    return run<TPolicy>(Pipeline::Apply(LINX_FORWARD(funcs)...)); // FIXME simplify implementation
  }

  /**
   * Apply an element-wise function and append the results.
   */
  auto append_apply(auto&&... funcs)
  {
    return apply<Append>(LINX_FORWARD(funcs)...);
  }

  /**
   * Apply an element-wise functino and prepend the results.
   */
  auto prepend_apply(auto&&... funcs)
  {
    return apply<Prepend>(LINX_FORWARD(funcs)...);
  }

  /**
   * Restrict the state domain.
   */
  template <typename T>
  auto domain(const Span<T>& span)
  {
    return make_state<Overwrite>("Domain", sequences_domain(span, std::make_index_sequence<sizeof...(TValues)>()));
  }

  /**
   * Restrict the state domain.
   */
  template <int N>
  auto domain(Box<N>&& box)
  {
    return run(Pipeline::Impl::RestrictImage(LINX_FORWARD(box))); // FIXME simplify implementation
  }

private:

  template <std::size_t... Is>
  auto sequences_domain(const auto& span, std::index_sequence<Is...>) const
  {
    return std::tuple(sequence_domain(span, std::get<Is>(m_values))...);
  }

  template <typename TIn>
  auto sequence_domain(const auto& span, const TIn& in) const
  {
    using T = std::remove_cvref_t<typename TIn::value_type>;
    return Sequence<T, -1>(label(in), span.size()).copy_from(in);
    // FIXME offset
  }

private:

  /**
   * Make a new multivalued state.
   */
  template <typename TPolicy, typename... Ts>
  auto make_state(const std::string& label, std::tuple<Ts...>&& values)
  {
    if constexpr (std::is_same_v<TPolicy, Overwrite>) {
      return Flow<TContext, Ts...>(m_context, label, LINX_FORWARD(values));
    } else if constexpr (std::is_same_v<TPolicy, Append>) {
      return make_state<Overwrite>(label, std::tuple_cat(m_values, LINX_FORWARD(values)));
    } else if constexpr (std::is_same_v<TPolicy, Prepend>) {
      return make_state<Overwrite>(label, std::tuple_cat(LINX_FORWARD(values), m_values));
    }
  }

  /**
   * Make a new single-valued state.
   */
  template <typename TPolicy>
  auto make_state(const std::string& label, auto&& value)
  {
    return make_state<TPolicy>(label, std::tuple(LINX_FORWARD(value)));
  }

  /**
   * Helper method to unroll indices.
   */
  template <std::integral auto... Is, typename TTask>
  static decltype(auto) eval(TTask&& task, auto&& values, std::index_sequence<Is...>)
  {
    return LINX_FORWARD(task)(std::get<Is>(LINX_FORWARD(values))...);
  }

  TContext m_context; ///< The workflow context
  std::tuple<TValues...> m_values; ///< The state values
};

template <typename TLogger = void>
Flow(const std::string&) -> Flow<FlowContext<void>>;

template <typename TLogger>
Flow(const std::string&, TLogger) -> Flow<FlowContext<TLogger>>;

template <typename T>
concept AnyState = is_specialization<Flow, T>;

} // namespace Linx

namespace std {

/**
 * @brief Enable structured bindings.
 */
template <typename TContext, typename... TValues>
struct tuple_size<Linx::Flow<TContext, TValues...>> : std::integral_constant<std::size_t, sizeof...(TValues)> {};

/**
 * @brief Enable structured bindings.
 */
template <std::size_t I, typename TContext, typename... TValues>
struct tuple_element<I, Linx::Flow<TContext, TValues...>> {
  using type = std::tuple_element_t<I, std::tuple<TValues...>>;
};

} // namespace std

#endif
