// SPDX-FileCopyrightText: Copyright (C) 2024, Antoine Basset
// SPDX-PackageSourceInfo: https://github.com/kabasset/Linx
// SPDX-License-Identifier: Apache-2.0

#ifndef LINX_RUN_PIPELINE_H
#define LINX_RUN_PIPELINE_H

#include "Linx/Data/Patch.h"

#include <ctime>
#include <iomanip> // put_time
#include <iostream>

namespace Linx {

/**
 * @brief Pipelining API.
 * 
 * A pipeline is a sequence of tasks which produce states.
 * The pipelining API provides a fluent syntax for the creation of pipelines.
 * 
 * The pipeline is started with some context and input states, and successive anonymous states are generated by user-provided tasks.
 * States hold arbitratily complex values, which are explicit inputs or the results of tasks.
 * The pipeline outputs are obtained through structured bindings, so that a typical pipeline is of the form:
 * 
 * \code
 * namespace P = Linx::Pipeline;
 * 
 * auto [out_0, out_1, ... , out_l] = P::Run("Pipeline name", logger) // Start pipeline
 *     | P::Input(in_0, in_1, ... , in_m) // Add inputs
 *     | task_0 | task_1 | ... | task_n; // Pipe tasks
 * \endcode
 * 
 * Tasks can act on one, some or all inputs at once, and return one or several outputs.
 * 
 * The pipe operator is a mere wrapper (similar to Unix' `|` or Elixir's `|>`):
 * if the pipeline i-th state is composed of values `value_0, value_1, ... , value_n`,
 * then `state_i | task_i` produces a (possibly multivalued) state `task_i(value_0, value_1, ... , value_n)`.
 * 
 * The above example corresponds to the following pseudo-code:
 * 
 * \code
 * tmp[0] = in
 * for i in [0, n]:
 *   tmp[i] = task[i](tmp[i-1])
 *   log task[i] parameters and elapsed time
 * out = tmp[n]
 * \endcode
 * 
 * where input, output and temporary states may be multivalued.
 */
namespace Pipeline {

/**
 * @brief Pipeline run context.
 */
template <typename TLogger>
class Run {
public:

  Run(const std::string& label, TLogger& logger = nullptr) : m_label(label), m_logger(logger) {}

  const std::string& label() const
  {
    return m_label;
  }

  void log(auto&&... args)
  {
    m_logger(m_label, LINX_FORWARD(args)...);
  }

private:

  std::string m_label;
  TLogger& m_logger; // FIXME enable owned logger
};

/**
 * @brief No-logger specialization.
 */
template <>
class Run<void> {
public:

  Run(const std::string& label) : m_label(label) {}

  const std::string& label() const
  {
    return m_label;
  }

  void log(auto&&...) {}

private:

  std::string m_label;
};

/**
 * @brief Input insertion task.
 */
template <typename... TValues> // TODO add insertion index, 0 by default
class Input {
public:

  Input(TValues... values) : m_values(LINX_MOVE(values)...) {}

  std::string label() const
  {
    return "Input"; // FIXME compose_label("Input", get<Is>(m_values))
  }

  auto operator()(auto&&... values) &&
  {
    return std::tuple_cat(std::make_tuple(LINX_FORWARD(values)...), LINX_MOVE(m_values));
  }

private:

  std::tuple<TValues...> m_values;
};

/**
 * @brief Pipeline state.
 */
template <typename TContext, typename... TValues>
class State {
public:

  State(TContext context, const std::string& message, TValues... values) :
      State(LINX_MOVE(context), message, std::make_tuple(LINX_MOVE(values)...))
  {}

  State(TContext context, const std::string& message, std::tuple<TValues...> values) :
      m_context(LINX_MOVE(context)),
      m_values(LINX_MOVE(values))
  {
    m_context.log(message);
  }

  State(const State&) = default;
  State(State&&) = default;
  State& operator=(const State&) = default;
  State& operator=(State&&) = default;

  template <std::size_t I>
  decltype(auto) get()
  {
    return std::get<I>(m_values);
  }

  template <typename TTask>
  auto operator|(TTask task) &&
  {
    auto task_label = label(task);
    auto out = eval(LINX_MOVE(task), LINX_MOVE(m_values), std::make_index_sequence<sizeof...(TValues)>());
    return Pipeline::State(LINX_MOVE(m_context), task_label, out); // FIXME NVCC is confused with CTAD here
  }

private:

  template <std::integral auto... Is, typename TTask>
  static decltype(auto) eval(TTask task, auto&& values, std::index_sequence<Is...>)
  {
    return LINX_MOVE(task)(std::get<Is>(LINX_FORWARD(values))...);
  }

  TContext m_context;
  std::tuple<TValues...> m_values;
  bool m_stopped = false;
};

/**
 * @brief Create a pipeline state from a context and input value.
 */
template <typename TLogger, typename TValue>
auto operator|(Run<TLogger> context, TValue&& value)
{
  return State(LINX_MOVE(context), "Start", LINX_FORWARD(value));
}

/**
 * @brief Create a pipeline state from a context and input values.
 */
template <typename TLogger, typename... TValues>
auto operator|(Run<TLogger> context, Input<TValues...>&& values)
{
  return State(LINX_MOVE(context), "Start") | LINX_FORWARD(values);
}

template <typename T>
concept AnyState = is_specialization<State, T>;

} // namespace Pipeline
} // namespace Linx

namespace std {

/**
 * @brief Enable structured bindings.
 */
template <typename TContext, typename... TValues>
struct tuple_size<Linx::Pipeline::State<TContext, TValues...>> :
    std::integral_constant<std::size_t, sizeof...(TValues)> {};

/**
 * @brief Enable structured bindings.
 */
template <std::size_t I, typename TContext, typename... TValues>
struct tuple_element<I, Linx::Pipeline::State<TContext, TValues...>> {
  using type = std::tuple_element_t<I, std::tuple<TValues...>>;
};

} // namespace std

#endif
